remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

title: DSA Collection
description: A comprehensive collection of Data Structures and Algorithms
show_downloads: false

navigation:
  - name: Home
    link: /
  - name: Hall of Fame
    link: /hall-of-fame
  - name: Contributing
    link: /contributing