name: Update Contributors

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Merged Pull Requests
        id: get_prs
        run: |
          PRS=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/admirerr/DSA-Collection/pulls?state=closed&sort=merged&direction=desc&per_page=100" | jq -r '.[] | select(.merged) | "\(.user.login), \(.user.avatar_url), \(.additions.contributors[].user.login)"')
          echo "::set-output name=prs::$PRS"

      - name: Update Contributors
        run: |
          set -x
          {
            echo "<div align=\"center\">";
            echo "  <a href=\"https://github.com/admirerr/DSA-Collection/graphs/contributors\">";
          } > contributors.html

          # Existing contributors from contributors.html
          existing_contributors=$(cat contributors.html | sed -n '/<img src=/p')

          # Merged pull request contributors
          echo "${{ steps.get_prs.outputs.prs }}" | \
          jq -r '.[] | select(.user.login != null and .additions.contributors[].user.login != null) | "\(.user.login), \(.user.avatar_url), \(.additions.contributors[].user.login)"' | \
          while read -r c; do
            if [ -z "$c" ]; then
              continue
            fi
            IFS=',' read -r login avatar_url contributions <<< "$c"
            if [[ ! $existing_contributors =~ $login ]]; then
              echo "    <img src=\"${avatar_url}&s=50\" width=\"50\" height=\"50\" alt=\"$\{login}\"/>" >> contributors.html
            fi
          done

          {
            echo "  </a>";
            echo "</div>";
          } >> contributors.html

          python << EOF
          import re

          with open('README.md', 'r+') as f:
              text = f.read()
              with open('contributors.html', 'r') as c:
                  contributors_html = c.read()

              # Replace everything between the tags
              new_text = re.sub(r'(<!-- CONTRIBUTORS_LIST -->)(.|\n)*(<!-- CONTRIBUTORS_LIST_END -->)',
                                f'\1\n{contributors_html}\n\3',
                                text)

              f.seek(0)
              f.write(new_text)
              f.truncate()
          EOF

      - name: Commit and Push Changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add contributors.html README.md
          git commit -m "Update contributors in README"
          git push