name: Update Contributors

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Contributors in HALL_OF_FAME.md and README.md
        run: |
          # Extract existing contributors from HALL_OF_FAME.md in TSV format
          EXISTING_CONTRIBUTORS=$(awk -F'[<>]' '
            /<div align=/{ 
              match($0, /\[([a-zA-Z0-9-]+)\]\((https:\/\/github\.com\/[a-zA-Z0-9-]+)\)/, arr);
              match($0, /<img src="([^"]+)"/, img);
              login = arr[1];
              url = arr[2];
              avatar = img[1];
              # contributions are in the next field after </div> | contributions |
              if(match($0, /\|[ ]*([0-9]+)[ ]*\|$/, c)) { contrib=c[1] } else { contrib=0 }
              if(login != "" && avatar != "" && url != "") print login "\t" avatar "\t" url "\t" contrib
            }' HALL_OF_FAME.md)

          # Fetch new contributors from GitHub
          NEW_CONTRIBUTORS=$(curl -s "https://api.github.com/repos/admirerr/DSA-Collection/contributors?per_page=100" \
            | jq -r '.[] | select(.type != "Bot") | [.login, .avatar_url, .html_url, .contributions] | @tsv')

          # Merge, remove duplicates, and sort by contributions descending
          ALL_CONTRIBUTORS=$(echo -e "$NEW_CONTRIBUTORS\n$EXISTING_CONTRIBUTORS" \
            | awk '!seen[$0]++' \
            | sort -k4,4nr)

          echo "$ALL_CONTRIBUTORS"

          # Build Hall of Fame table (full)
          TABLE=$(echo "$ALL_CONTRIBUTORS" | awk -F'\t' '{printf "| <div align=\"center\"><img src=\"%s\" width=\"50\" height=\"50\"/><br>[%s](%s)</div> | %s |\n", $2, $1, $3, $4}')

          # Build avatars row for README (limit to 20)
          AVATARS=$(echo "$ALL_CONTRIBUTORS" | head -n 20 | awk -F'\t' '{printf "[<img src=\"%s\" width=\"50\" height=\"50\" alt=\"%s\"/>](%s) ", $2, $1, $3}')

          # ---- Update Hall of Fame ----
          awk -v table="$TABLE" '
            /Contributor \| Contributions/ {
              print;
              print "|-------------|---------------|";
              print table;
              in_block=1; next;
            }
            in_block && /^\|/ {next}
            {print}
          ' HALL_OF_FAME.md > temp && mv temp HALL_OF_FAME.md

          # ---- Update README ----
          awk -v avatars="$AVATARS" '
            /<!-- CONTRIBUTORS START -->/ {
              print;
              print avatars;
              in_block=1; next;
            }
            in_block && /<!-- CONTRIBUTORS END -->/ {print; in_block=0; next}
            in_block {next}
            {print}
          ' README.md > temp && mv temp README.md

      - name: Update Implementation Counts
        run: |
          sed -i 's/| 🎯 \*\*Total Implementations\*\* | [0-9]\+ |/| 🎯 **Total Implementations** | 22 |/' HALL_OF_FAME.md
          sed -i '/### Python/{n;s/- Implementations: [0-9]\+/- Implementations: 6/}' HALL_OF_FAME.md
          sed -i '/### C++/{n;s/- Implementations: [0-9]\+/- Implementations: 4/}' HALL_OF_FAME.md
          sed -i '/### Java/{n;s/- Implementations: [0-9]\+/- Implementations: 12/}' HALL_OF_FAME.md

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add HALL_OF_FAME.md README.md
          git commit -m "Update contributors and implementations" || echo "No changes to commit"
          git push
