name: 🏆 Update Contributors

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    # Only run when PR is merged or manually triggered
    # Skip if the commit message contains [skip ci] or is from the bot itself
    if: |
      (github.event_name == 'workflow_dispatch' ||
       (github.event_name == 'pull_request' && github.event.pull_request.merged == true)) &&
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, 'Auto-update contributor')

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: 🏆 Update contributors list
      run: |
        echo "🔍 Fetching contributors from GitHub API..."
        
        # Fetch contributors and create HTML
        curl -s "https://api.github.com/repos/${{ github.repository }}/contributors?per_page=100" | \
        jq -r '.[] | select(.type != "Bot") | "<img src=\"\(.avatar_url)&s=50\" width=\"50\" height=\"50\" alt=\"\(.login)\" />"' | \
        {
          echo "<div align=\"center\">"
          echo "  <a href=\"https://github.com/${{ github.repository }}/graphs/contributors\">"
          cat
          echo "  </a>"
          echo "</div>"
        } > contributors.html

        echo "📄 Contributors HTML generated"
        echo "---"
        cat contributors.html
        echo "---"

        # Verify README.md exists
        if [ ! -f "README.md" ]; then
          echo "❌ ERROR: README.md not found!"
          exit 1
        fi

        # Check if tags exist
        if ! grep -q "<!-- CONTRIBUTORS_LIST -->" README.md; then
          echo "❌ ERROR: <!-- CONTRIBUTORS_LIST --> tag not found in README.md"
          exit 1
        fi
        
        if ! grep -q "<!-- CONTRIBUTORS_LIST_END -->" README.md; then
          echo "❌ ERROR: <!-- CONTRIBUTORS_LIST_END --> tag not found in README.md"
          exit 1
        fi
        
        echo "✅ Both tags found in README.md"
        echo "🔄 Updating README.md with contributors..."

        # Update README.md
        python3 << 'EOF'
        import re
        import sys

        try:
            with open('README.md', 'r', encoding='utf-8') as f:
                text = f.read()
            
            with open('contributors.html', 'r', encoding='utf-8') as c:
                contributors_html = c.read().strip()
            
            new_text = re.sub(
                r'<!-- CONTRIBUTORS_LIST -->.*?<!-- CONTRIBUTORS_LIST_END -->',
                f'<!-- CONTRIBUTORS_LIST -->\n{contributors_html}\n<!-- CONTRIBUTORS_LIST_END -->',
                text,
                flags=re.DOTALL
            )
            
            with open('README.md', 'w', encoding='utf-8') as f:
                f.write(new_text)
            
            print("✅ README.md updated successfully!")
            
        except Exception as e:
            print(f"❌ ERROR: {str(e)}")
            sys.exit(1)
        EOF

        echo "✅ Contributors list update completed!"

    - name: 📈 Update language statistics
      run: |
        echo "📈 Updating language statistics..."

        # Count files by language
        cpp_files=$(find CPP/ -name "*.cpp" 2>/dev/null | wc -l || echo 0)
        java_files=$(find Java/ -name "*.java" 2>/dev/null | wc -l || echo 0)
        python_files=$(find Python/ -name "*.py" 2>/dev/null | wc -l || echo 0)

        total_implementations=$((cpp_files + java_files + python_files))

        echo "📊 Language Statistics:"
        echo "C++: $cpp_files files"
        echo "Java: $java_files files"
        echo "Python: $python_files files"
        echo "Total: $total_implementations implementations"

        supported_languages=3

        # Update README stats
        if [ -f "README.md" ]; then
          sed -i -e "s/💻 \*\*[0-9]*+ Languages\*\*/💻 **${supported_languages}+ Languages**/g" \
                   -e "s/✨ \*\*[0-9]*+ Total Implementations\*\*/✨ **${total_implementations}+ Total Implementations**/g" README.md
        fi

    - name: 📅 Update last modified date
      run: |
        echo "📅 Updating last modified date..."
        current_date=$(date +"%B %Y")

        if [ -f "HALL_OF_FAME.md" ]; then
          sed -i "s/\*Last updated: .* [0-9]*\*/\*Last updated: $current_date\*/g" HALL_OF_FAME.md
          echo "✅ Updated last modified date in HALL_OF_FAME.md"
        fi

    - name: 🔍 Check for changes
      id: changes
      run: |
        if ! git diff --quiet; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "📝 Changes detected"
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "ℹ️  No changes needed"
        fi

    - name: 💾 Create Pull Request
      if: steps.changes.outputs.has_changes == 'true'
      id: cpr
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "🏆 Auto-update contributor statistics"
        committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
        author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
        branch: contributors-auto-update
        delete-branch: true
        title: "🏆 Update Contributor Statistics"
        body: |
          ## 🤖 Automated Contributor Update
          
          This PR automatically updates the contributors list after a PR was merged.
          
          ### 📋 What's Updated:
          - 👥 Contributors avatars in README.md
          - 📊 Language statistics
          - 📅 Last modified date
          
          ### 🔍 Trigger Information:
          ${{ github.event_name == 'pull_request' && format('- ✅ Triggered by merged PR #{0} by @{1}', github.event.pull_request.number, github.event.pull_request.user.login) || '- 🔧 Triggered manually' }}
          
          ### ✅ Action Required:
          **Simply click "Merge pull request"** to apply the contributor updates.
          
          ---
          <sub>🤖 Automated PR by GitHub Actions | This workflow only runs when PRs are merged</sub>
        labels: |
          documentation
          automated
    
    - name: 📊 Output PR Details
      if: steps.changes.outputs.has_changes == 'true'
      run: |
        if [ -n "${{ steps.cpr.outputs.pull-request-number }}" ]; then
          echo "✅ PR #${{ steps.cpr.outputs.pull-request-number }} ${{ steps.cpr.outputs.pull-request-operation }}"
          echo "🔗 ${{ steps.cpr.outputs.pull-request-url }}"
        else
          echo "ℹ️ PR already exists with these changes"
        fi

    - name: 📋 Summary
      run: |
        echo "## 🏆 Contributors Update" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ steps.changes.outputs.has_changes }}" == "true" ]; then
          if [ -n "${{ steps.cpr.outputs.pull-request-number }}" ]; then
            echo "✅ **Status**: Pull request ${{ steps.cpr.outputs.pull-request-operation }}" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "🔗 **PR**: [#${{ steps.cpr.outputs.pull-request-number }}](${{ steps.cpr.outputs.pull-request-url }})" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            
            if [ "${{ github.event_name }}" == "pull_request" ]; then
              echo "📌 **Triggered by**: PR #${{ github.event.pull_request.number }}" >> $GITHUB_STEP_SUMMARY
              echo "👤 **New contributor**: @${{ github.event.pull_request.user.login }}" >> $GITHUB_STEP_SUMMARY
            else
              echo "📌 **Triggered by**: Push to main" >> $GITHUB_STEP_SUMMARY
            fi
            
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### ✅ Next Step" >> $GITHUB_STEP_SUMMARY
            echo "Review and merge the PR to update the contributors list!" >> $GITHUB_STEP_SUMMARY
          else
            echo "ℹ️ **Status**: PR already exists with the same changes" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Check existing PRs for contributors updates." >> $GITHUB_STEP_SUMMARY
          fi
        else
          echo "✨ **Status**: No changes needed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Contributors list is already up-to-date!" >> $GITHUB_STEP_SUMMARY
        fi