name: 🏆 Update Contributors

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
    - name: Run test
      run: echo "The update-contributors job is running!"